base/{sim,steer}: override, const, cleanup
FairRootGroup/FairRoot pull request #1179
Opened 2022-05-05 11:11 UTC by ChristianTackeGSI

* FairVoume: Major cleanup
* Rest: override

---

Checklist:

* [X] Rebased against `dev` branch
* [X] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [X] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

2022-05-05 14:44 UTC, fuhlig1 commented on base/sim/FairVolume.cxx
> +    , fMotherId(-1)
I am not 100% sure but -1 should be okay for both constructors. I will try to have a deeper look tomorrow.

2022-05-05 21:31 UTC, ChristianTackeGSI commented on base/sim/FairVolume.h
> +    FairVolume(TString name, Int_t id = 0, Int_t ModId = 0, FairModule* fMod = nullptr);
@fuhlig1 Can you please also comment on `fModId`?

The default `()` constructor sets it to `-1` (that's why I have set the member initializer to that value), but the default argument for this constructor also has a `0`?

2022-06-08 14:08 UTC, fuhlig1 commented on base/sim/FairVolume.cxx
> +    , fMotherId(-1)
I checked and couldn' t find any place where the the value is checked to be 0 or -1.

2022-06-08 14:09 UTC, fuhlig1 commented on base/sim/FairVolume.cxx
> +    , fMotherId(-1)
Can be put in the header file as -1.

2022-06-08 14:10 UTC, fuhlig1 requested changes
Can be merged after fMotherID is initialized in the header file.

2022-06-08 14:55 UTC, ChristianTackeGSI commented
Okay, added the member initialiser for `fMotherID{-1}` and rebased.

2022-06-08 17:44 UTC, fuhlig1 approved these changes

2022-06-08 17:44 UTC, merged